// Auto-generated — daftar kota Indonesia + tarif ongkir per zona per kurir
export const CITIES = [
  ['Jakarta Pusat','DKI Jakarta',1],
  ['Jakarta Utara','DKI Jakarta',1],
  ['Jakarta Barat','DKI Jakarta',1],
  ['Jakarta Selatan','DKI Jakarta',1],
  ['Jakarta Timur','DKI Jakarta',1],
  ['Kepulauan Seribu','DKI Jakarta',1],
  ['Bogor','Jawa Barat',1],
  ['Depok','Jawa Barat',1],
  ['Tangerang','Banten',1],
  ['Tangerang Selatan','Banten',1],
  ['Bekasi','Jawa Barat',1],
  ['Bandung','Jawa Barat',2],
  ['Bandung Barat','Jawa Barat',2],
  ['Cimahi','Jawa Barat',2],
  ['Cianjur','Jawa Barat',2],
  ['Sukabumi','Jawa Barat',2],
  ['Garut','Jawa Barat',2],
  ['Tasikmalaya','Jawa Barat',2],
  ['Ciamis','Jawa Barat',2],
  ['Pangandaran','Jawa Barat',2],
  ['Kuningan','Jawa Barat',2],
  ['Cirebon','Jawa Barat',2],
  ['Majalengka','Jawa Barat',2],
  ['Indramayu','Jawa Barat',2],
  ['Purwakarta','Jawa Barat',2],
  ['Karawang','Jawa Barat',2],
  ['Subang','Jawa Barat',2],
  ['Sumedang','Jawa Barat',2],
  ['Banjar','Jawa Barat',2],
  ['Cilegon','Banten',2],
  ['Serang','Banten',2],
  ['Pandeglang','Banten',2],
  ['Lebak','Banten',2],
  ['Semarang','Jawa Tengah',2],
  ['Surakarta','Jawa Tengah',2],
  ['Salatiga','Jawa Tengah',2],
  ['Magelang','Jawa Tengah',2],
  ['Pekalongan','Jawa Tengah',2],
  ['Tegal','Jawa Tengah',2],
  ['Banyumas','Jawa Tengah',2],
  ['Cilacap','Jawa Tengah',2],
  ['Kebumen','Jawa Tengah',2],
  ['Purworejo','Jawa Tengah',2],
  ['Klaten','Jawa Tengah',2],
  ['Boyolali','Jawa Tengah',2],
  ['Sukoharjo','Jawa Tengah',2],
  ['Wonogiri','Jawa Tengah',2],
  ['Karanganyar','Jawa Tengah',2],
  ['Sragen','Jawa Tengah',2],
  ['Grobogan','Jawa Tengah',2],
  ['Blora','Jawa Tengah',2],
  ['Rembang','Jawa Tengah',2],
  ['Pati','Jawa Tengah',2],
  ['Kudus','Jawa Tengah',2],
  ['Jepara','Jawa Tengah',2],
  ['Demak','Jawa Tengah',2],
  ['Kendal','Jawa Tengah',2],
  ['Batang','Jawa Tengah',2],
  ['Pemalang','Jawa Tengah',2],
  ['Brebes','Jawa Tengah',2],
  ['Temanggung','Jawa Tengah',2],
  ['Wonosobo','Jawa Tengah',2],
  ['Banjarnegara','Jawa Tengah',2],
  ['Purbalingga','Jawa Tengah',2],
  ['Yogyakarta','DI Yogyakarta',2],
  ['Sleman','DI Yogyakarta',2],
  ['Bantul','DI Yogyakarta',2],
  ['Kulon Progo','DI Yogyakarta',2],
  ['Gunung Kidul','DI Yogyakarta',2],
  ['Surabaya','Jawa Timur',3],
  ['Sidoarjo','Jawa Timur',3],
  ['Gresik','Jawa Timur',3],
  ['Mojokerto','Jawa Timur',3],
  ['Malang','Jawa Timur',3],
  ['Batu','Jawa Timur',3],
  ['Pasuruan','Jawa Timur',3],
  ['Probolinggo','Jawa Timur',3],
  ['Jember','Jawa Timur',3],
  ['Banyuwangi','Jawa Timur',3],
  ['Situbondo','Jawa Timur',3],
  ['Bondowoso','Jawa Timur',3],
  ['Lumajang','Jawa Timur',3],
  ['Kediri','Jawa Timur',3],
  ['Blitar','Jawa Timur',3],
  ['Tulungagung','Jawa Timur',3],
  ['Trenggalek','Jawa Timur',3],
  ['Ponorogo','Jawa Timur',3],
  ['Madiun','Jawa Timur',3],
  ['Ngawi','Jawa Timur',3],
  ['Magetan','Jawa Timur',3],
  ['Pacitan','Jawa Timur',3],
  ['Bojonegoro','Jawa Timur',3],
  ['Tuban','Jawa Timur',3],
  ['Lamongan','Jawa Timur',3],
  ['Bangkalan','Jawa Timur',3],
  ['Sampang','Jawa Timur',3],
  ['Pamekasan','Jawa Timur',3],
  ['Sumenep','Jawa Timur',3],
  ['Denpasar','Bali',3],
  ['Badung','Bali',3],
  ['Gianyar','Bali',3],
  ['Tabanan','Bali',3],
  ['Buleleng','Bali',3],
  ['Bangli','Bali',3],
  ['Klungkung','Bali',3],
  ['Karangasem','Bali',3],
  ['Jembrana','Bali',3],
  ['Palembang','Sumatera Selatan',4],
  ['Prabumulih','Sumatera Selatan',4],
  ['Pagar Alam','Sumatera Selatan',4],
  ['Lubuklinggau','Sumatera Selatan',4],
  ['Banyuasin','Sumatera Selatan',4],
  ['Ogan Ilir','Sumatera Selatan',4],
  ['OKU','Sumatera Selatan',4],
  ['OKI','Sumatera Selatan',4],
  ['Muara Enim','Sumatera Selatan',4],
  ['Lahat','Sumatera Selatan',4],
  ['Musi Rawas','Sumatera Selatan',4],
  ['Musi Banyuasin','Sumatera Selatan',4],
  ['Bandar Lampung','Lampung',4],
  ['Metro','Lampung',4],
  ['Lampung Selatan','Lampung',4],
  ['Lampung Tengah','Lampung',4],
  ['Lampung Utara','Lampung',4],
  ['Lampung Barat','Lampung',4],
  ['Lampung Timur','Lampung',4],
  ['Pesawaran','Lampung',4],
  ['Pringsewu','Lampung',4],
  ['Tanggamus','Lampung',4],
  ['Way Kanan','Lampung',4],
  ['Bengkulu','Bengkulu',4],
  ['Rejang Lebong','Bengkulu',4],
  ['Bengkulu Utara','Bengkulu',4],
  ['Bengkulu Selatan','Bengkulu',4],
  ['Seluma','Bengkulu',4],
  ['Muko-Muko','Bengkulu',4],
  ['Kaur','Bengkulu',4],
  ['Lebong','Bengkulu',4],
  ['Kepahiang','Bengkulu',4],
  ['Jambi','Jambi',4],
  ['Sungai Penuh','Jambi',4],
  ['Muaro Jambi','Jambi',4],
  ['Batanghari','Jambi',4],
  ['Tanjung Jabung','Jambi',4],
  ['Sarolangun','Jambi',4],
  ['Merangin','Jambi',4],
  ['Bungo','Jambi',4],
  ['Tebo','Jambi',4],
  ['Kerinci','Jambi',4],
  ['Medan','Sumatera Utara',5],
  ['Binjai','Sumatera Utara',5],
  ['Tebing Tinggi','Sumatera Utara',5],
  ['Pematangsiantar','Sumatera Utara',5],
  ['Tanjungbalai','Sumatera Utara',5],
  ['Sibolga','Sumatera Utara',5],
  ['Padangsidimpuan','Sumatera Utara',5],
  ['Deli Serdang','Sumatera Utara',5],
  ['Langkat','Sumatera Utara',5],
  ['Karo','Sumatera Utara',5],
  ['Simalungun','Sumatera Utara',5],
  ['Toba','Sumatera Utara',5],
  ['Asahan','Sumatera Utara',5],
  ['Labuhanbatu','Sumatera Utara',5],
  ['Mandailing Natal','Sumatera Utara',5],
  ['Tapanuli','Sumatera Utara',5],
  ['Nias','Sumatera Utara',5],
  ['Padang','Sumatera Barat',5],
  ['Bukittinggi','Sumatera Barat',5],
  ['Payakumbuh','Sumatera Barat',5],
  ['Solok','Sumatera Barat',5],
  ['Padang Panjang','Sumatera Barat',5],
  ['Pariaman','Sumatera Barat',5],
  ['Agam','Sumatera Barat',5],
  ['Tanah Datar','Sumatera Barat',5],
  ['Pasaman','Sumatera Barat',5],
  ['Mentawai','Sumatera Barat',5],
  ['Banda Aceh','Aceh',5],
  ['Lhokseumawe','Aceh',5],
  ['Langsa','Aceh',5],
  ['Sabang','Aceh',5],
  ['Aceh Besar','Aceh',5],
  ['Pidie','Aceh',5],
  ['Aceh Utara','Aceh',5],
  ['Aceh Timur','Aceh',5],
  ['Aceh Tengah','Aceh',5],
  ['Aceh Singkil','Aceh',5],
  ['Bener Meriah','Aceh',5],
  ['Pekanbaru','Riau',5],
  ['Dumai','Riau',5],
  ['Bengkalis','Riau',5],
  ['Siak','Riau',5],
  ['Kampar','Riau',5],
  ['Rokan Hulu','Riau',5],
  ['Rokan Hilir','Riau',5],
  ['Pelalawan','Riau',5],
  ['Indragiri','Riau',5],
  ['Kepulauan Meranti','Riau',5],
  ['Batam','Kepulauan Riau',5],
  ['Tanjung Pinang','Kepulauan Riau',5],
  ['Karimun','Kepulauan Riau',5],
  ['Bintan','Kepulauan Riau',5],
  ['Natuna','Kepulauan Riau',5],
  ['Lingga','Kepulauan Riau',5],
  ['Pontianak','Kalimantan Barat',5],
  ['Singkawang','Kalimantan Barat',5],
  ['Kubu Raya','Kalimantan Barat',5],
  ['Ketapang','Kalimantan Barat',5],
  ['Sanggau','Kalimantan Barat',5],
  ['Sintang','Kalimantan Barat',5],
  ['Sambas','Kalimantan Barat',5],
  ['Balikpapan','Kalimantan Timur',5],
  ['Samarinda','Kalimantan Timur',5],
  ['Bontang','Kalimantan Timur',5],
  ['Kutai Kertanegara','Kalimantan Timur',5],
  ['Kutai Timur','Kalimantan Timur',5],
  ['Berau','Kalimantan Timur',5],
  ['Paser','Kalimantan Timur',5],
  ['Penajam','Kalimantan Timur',5],
  ['Banjarmasin','Kalimantan Selatan',5],
  ['Banjarbaru','Kalimantan Selatan',5],
  ['Banjar','Kalimantan Selatan',5],
  ['Barito Kuala','Kalimantan Selatan',5],
  ['Tapin','Kalimantan Selatan',5],
  ['Hulu Sungai','Kalimantan Selatan',5],
  ['Tanah Laut','Kalimantan Selatan',5],
  ['Kotabaru','Kalimantan Selatan',5],
  ['Palangkaraya','Kalimantan Tengah',5],
  ['Sampit','Kalimantan Tengah',5],
  ['Pangkalan Bun','Kalimantan Tengah',5],
  ['Kapuas','Kalimantan Tengah',5],
  ['Barito Utara','Kalimantan Tengah',5],
  ['Katingan','Kalimantan Tengah',5],
  ['Tanjung Selor','Kalimantan Utara',5],
  ['Tarakan','Kalimantan Utara',5],
  ['Bulungan','Kalimantan Utara',5],
  ['Malinau','Kalimantan Utara',5],
  ['Nunukan','Kalimantan Utara',5],
  ['Makassar','Sulawesi Selatan',6],
  ['Parepare','Sulawesi Selatan',6],
  ['Palopo','Sulawesi Selatan',6],
  ['Gowa','Sulawesi Selatan',6],
  ['Maros','Sulawesi Selatan',6],
  ['Takalar','Sulawesi Selatan',6],
  ['Bone','Sulawesi Selatan',6],
  ['Wajo','Sulawesi Selatan',6],
  ['Luwu','Sulawesi Selatan',6],
  ['Tana Toraja','Sulawesi Selatan',6],
  ['Manado','Sulawesi Utara',6],
  ['Bitung','Sulawesi Utara',6],
  ['Tomohon','Sulawesi Utara',6],
  ['Minahasa','Sulawesi Utara',6],
  ['Bolaang Mongondow','Sulawesi Utara',6],
  ['Kepulauan Sangihe','Sulawesi Utara',6],
  ['Talaud','Sulawesi Utara',6],
  ['Gorontalo','Gorontalo',6],
  ['Bone Bolango','Gorontalo',6],
  ['Boalemo','Gorontalo',6],
  ['Palu','Sulawesi Tengah',6],
  ['Donggala','Sulawesi Tengah',6],
  ['Poso','Sulawesi Tengah',6],
  ['Toli-Toli','Sulawesi Tengah',6],
  ['Morowali','Sulawesi Tengah',6],
  ['Parigi Moutong','Sulawesi Tengah',6],
  ['Banggai','Sulawesi Tengah',6],
  ['Kendari','Sulawesi Tenggara',6],
  ['Baubau','Sulawesi Tenggara',6],
  ['Kolaka','Sulawesi Tenggara',6],
  ['Konawe','Sulawesi Tenggara',6],
  ['Muna','Sulawesi Tenggara',6],
  ['Buton','Sulawesi Tenggara',6],
  ['Wakatobi','Sulawesi Tenggara',6],
  ['Mamuju','Sulawesi Barat',6],
  ['Polewali Mandar','Sulawesi Barat',6],
  ['Majene','Sulawesi Barat',6],
  ['Mataram','Nusa Tenggara Barat',6],
  ['Bima','Nusa Tenggara Barat',6],
  ['Sumbawa','Nusa Tenggara Barat',6],
  ['Dompu','Nusa Tenggara Barat',6],
  ['Lombok Barat','Nusa Tenggara Barat',6],
  ['Lombok Tengah','Nusa Tenggara Barat',6],
  ['Lombok Timur','Nusa Tenggara Barat',6],
  ['Kupang','Nusa Tenggara Timur',6],
  ['Ende','Nusa Tenggara Timur',6],
  ['Maumere','Nusa Tenggara Timur',6],
  ['Atambua','Nusa Tenggara Timur',6],
  ['Ruteng','Nusa Tenggara Timur',6],
  ['Waingapu','Nusa Tenggara Timur',6],
  ['Labuan Bajo','Nusa Tenggara Timur',6],
  ['Soe','Nusa Tenggara Timur',6],
  ['Bajawa','Nusa Tenggara Timur',6],
  ['Larantuka','Nusa Tenggara Timur',6],
  ['Ambon','Maluku',7],
  ['Tual','Maluku',7],
  ['Maluku Tengah','Maluku',7],
  ['Seram','Maluku',7],
  ['Buru','Maluku',7],
  ['Kepulauan Aru','Maluku',7],
  ['Ternate','Maluku Utara',7],
  ['Tidore','Maluku Utara',7],
  ['Halmahera','Maluku Utara',7],
  ['Morotai','Maluku Utara',7],
  ['Jayapura','Papua',7],
  ['Biak','Papua',7],
  ['Timika','Papua',7],
  ['Nabire','Papua',7],
  ['Merauke','Papua',7],
  ['Sarmi','Papua',7],
  ['Keerom','Papua',7],
  ['Yapen','Papua',7],
  ['Mamberamo','Papua',7],
  ['Supiori','Papua',7],
  ['Waropen','Papua',7],
  ['Sorong','Papua Barat',7],
  ['Manokwari','Papua Barat',7],
  ['Fakfak','Papua Barat',7],
  ['Kaimana','Papua Barat',7],
  ['Raja Ampat','Papua Barat',7],
  ['Teluk Bintuni','Papua Barat',7],
  ['Teluk Wondama','Papua Barat',7],
  ['Sorong Selatan','Papua Barat',7],
  ['Tambrauw','Papua Barat',7],
  ['Maybrat','Papua Barat',7],
];

export const RATES = [
  { courier:'jne', name:'JNE REG', costs:[9000, 11000, 14000, 18000, 24000, 32000, 45000], ets:["1-2", "1-3", "1-3", "2-4", "2-5", "3-6", "4-8"] },
  { courier:'jnt', name:'J&T Express', costs:[8000, 10000, 13000, 17000, 23000, 30000, 43000], ets:["1-2", "1-3", "1-3", "2-4", "2-5", "3-6", "4-8"] },
  { courier:'sicepat', name:'SiCepat REG', costs:[7000, 9000, 12000, 16000, 22000, 29000, 40000], ets:["1-2", "1-2", "1-3", "2-4", "2-5", "3-6", "4-7"] },
  { courier:'pos', name:'POS Kilat Khusus', costs:[8000, 10000, 13000, 17000, 22000, 28000, 38000], ets:["2-3", "2-4", "2-4", "3-5", "3-6", "4-7", "5-9"] },
  { courier:'idexpress', name:'ID Express', costs:[6000, 8000, 11000, 15000, 0, 0, 0], ets:["1-2", "1-2", "1-3", "2-4", "-", "-", "-"] },
];

export const COURIER_NAMES = {
  'jne': 'JNE REG',
  'jnt': 'J&T Express',
  'sicepat': 'SiCepat REG',
  'pos': 'POS Kilat Khusus',
  'idexpress': 'ID Express',
};
